### PR TITLE
Expose blockchain classes to browser

### PR DESCRIPTION
**Pull request by xeroc**
add toByteBuffer() to all classes
offer interface to blockchain

### CODE REVIEW

**Comment by jcalfee** [comment]
I think you'll eventually find that after fighting with the ByteBuffer object and how it handles surplus buffering that it is best to accept a ByteBuffer object in the toByteBuffer method.  So, you will construct the ByteBuffer once and pass it to the toByteBuffer method which will call each other toByteBuffer(b) methods for the entire structure passing the same ByteBuffer object.  This should be how the other toByteBuffer methods are written.  An exception might be a outermost object, but even then signed transactions get wrapped into other things like mail messages so there really is no outermost starting point.

**Comment by jcalfee** [comment]
I see something else.. you forked from jcalfee/bitshares-js, but the main repository is at bitshares/bitshares-js...  Sorry about the confusion.  I put a link at jcalfee/bitshares-js to the main repository to try and avoid this.  If you want me to push updates to my repo let me know.

**Comment by jcalfee** [comment]
I removed a message about toByteBuffer... thanks for the pull request, I'm reviewing.

**Comment by jcalfee** [comment]
Many toByteBuffer have already been added at bitshares/bitshares-js .. better if you can change your fork to point to that repo.  Also, appendByteBuffer methods were necessary to deal with the way ByteBuffer works.

**Comment by xeroc** [comment]
@jcalfee .. I see .. different repo .. gonna change the pull request
I justed noticed that the bitshares/bitshares-js was missing some toByteBuffer and thus toHex() failed

**Pull request closed without merging**
